name: Lint Domain Connect Templates

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Install dc-template-linter
        run: go install github.com/Domain-Connect/dc-template-linter@latest

      - name: Lint Templates
        run: ${{ github.workspace }}/go/bin/dc-template-linter ./*.json

#      - name: Comment PR with Linter Results
#        # Use a GitHub Action or script to format and post the linter results as a comment on the PR
#        uses: some-action/to-comment-pr@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          message: |
#            Linter Results:
#            # Include linter results here
